// Code generated by protoc-gen-go. DO NOT EDIT.
// source: amiibo/v1/amiibo.proto

package amiibov1

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Amiibo_Type int32

const (
	Amiibo_UNSPECIFIED Amiibo_Type = 0
	Amiibo_CARD        Amiibo_Type = 1
	Amiibo_FIGURE      Amiibo_Type = 2
	Amiibo_YARN        Amiibo_Type = 3
)

var Amiibo_Type_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "CARD",
	2: "FIGURE",
	3: "YARN",
}

var Amiibo_Type_value = map[string]int32{
	"UNSPECIFIED": 0,
	"CARD":        1,
	"FIGURE":      2,
	"YARN":        3,
}

func (x Amiibo_Type) String() string {
	return proto.EnumName(Amiibo_Type_name, int32(x))
}

func (Amiibo_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59da289444c690ce, []int{2, 0}
}

type GetAmiiboRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAmiiboRequest) Reset()         { *m = GetAmiiboRequest{} }
func (m *GetAmiiboRequest) String() string { return proto.CompactTextString(m) }
func (*GetAmiiboRequest) ProtoMessage()    {}
func (*GetAmiiboRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59da289444c690ce, []int{0}
}

func (m *GetAmiiboRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAmiiboRequest.Unmarshal(m, b)
}
func (m *GetAmiiboRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAmiiboRequest.Marshal(b, m, deterministic)
}
func (m *GetAmiiboRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAmiiboRequest.Merge(m, src)
}
func (m *GetAmiiboRequest) XXX_Size() int {
	return xxx_messageInfo_GetAmiiboRequest.Size(m)
}
func (m *GetAmiiboRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAmiiboRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAmiiboRequest proto.InternalMessageInfo

func (m *GetAmiiboRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAmiiboResponse struct {
	Amiibo               []*Amiibo `protobuf:"bytes,1,rep,name=amiibo,proto3" json:"amiibo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAmiiboResponse) Reset()         { *m = GetAmiiboResponse{} }
func (m *GetAmiiboResponse) String() string { return proto.CompactTextString(m) }
func (*GetAmiiboResponse) ProtoMessage()    {}
func (*GetAmiiboResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59da289444c690ce, []int{1}
}

func (m *GetAmiiboResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAmiiboResponse.Unmarshal(m, b)
}
func (m *GetAmiiboResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAmiiboResponse.Marshal(b, m, deterministic)
}
func (m *GetAmiiboResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAmiiboResponse.Merge(m, src)
}
func (m *GetAmiiboResponse) XXX_Size() int {
	return xxx_messageInfo_GetAmiiboResponse.Size(m)
}
func (m *GetAmiiboResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAmiiboResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAmiiboResponse proto.InternalMessageInfo

func (m *GetAmiiboResponse) GetAmiibo() []*Amiibo {
	if m != nil {
		return m.Amiibo
	}
	return nil
}

type Amiibo struct {
	Character            string      `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AmiiboSerioes        string      `protobuf:"bytes,3,opt,name=amiibo_serioes,json=amiiboSerioes,proto3" json:"amiibo_serioes,omitempty"`
	ImageUrl             string      `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type                 Amiibo_Type `protobuf:"varint,5,opt,name=type,proto3,enum=clutch.amiibi.v1.Amiibo_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Amiibo) Reset()         { *m = Amiibo{} }
func (m *Amiibo) String() string { return proto.CompactTextString(m) }
func (*Amiibo) ProtoMessage()    {}
func (*Amiibo) Descriptor() ([]byte, []int) {
	return fileDescriptor_59da289444c690ce, []int{2}
}

func (m *Amiibo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amiibo.Unmarshal(m, b)
}
func (m *Amiibo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amiibo.Marshal(b, m, deterministic)
}
func (m *Amiibo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amiibo.Merge(m, src)
}
func (m *Amiibo) XXX_Size() int {
	return xxx_messageInfo_Amiibo.Size(m)
}
func (m *Amiibo) XXX_DiscardUnknown() {
	xxx_messageInfo_Amiibo.DiscardUnknown(m)
}

var xxx_messageInfo_Amiibo proto.InternalMessageInfo

func (m *Amiibo) GetCharacter() string {
	if m != nil {
		return m.Character
	}
	return ""
}

func (m *Amiibo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Amiibo) GetAmiiboSerioes() string {
	if m != nil {
		return m.AmiiboSerioes
	}
	return ""
}

func (m *Amiibo) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Amiibo) GetType() Amiibo_Type {
	if m != nil {
		return m.Type
	}
	return Amiibo_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("clutch.amiibi.v1.Amiibo_Type", Amiibo_Type_name, Amiibo_Type_value)
	proto.RegisterType((*GetAmiiboRequest)(nil), "clutch.amiibi.v1.GetAmiiboRequest")
	proto.RegisterType((*GetAmiiboResponse)(nil), "clutch.amiibi.v1.GetAmiiboResponse")
	proto.RegisterType((*Amiibo)(nil), "clutch.amiibi.v1.Amiibo")
}

func init() {
	proto.RegisterFile("amiibo/v1/amiibo.proto", fileDescriptor_59da289444c690ce)
}

var fileDescriptor_59da289444c690ce = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x1d, 0x8a, 0x58, 0xce, 0x8d, 0x57, 0x9c, 0x18, 0xc5, 0xde, 0x6b, 0x24, 0x18, 0x93,
	0xc6, 0x05, 0x48, 0x5d, 0x98, 0xb8, 0xa3, 0x2d, 0x6d, 0xd8, 0x34, 0x0d, 0xb5, 0x0b, 0xdd, 0x34,
	0x53, 0x9c, 0xd0, 0x49, 0x28, 0x83, 0x30, 0x90, 0x74, 0xdb, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x57,
	0x3e, 0x82, 0x2b, 0xd3, 0x99, 0xd6, 0x9a, 0x1a, 0xef, 0xee, 0xf0, 0x9d, 0xff, 0x9c, 0xf3, 0x87,
	0x7f, 0xe0, 0x29, 0xd9, 0x32, 0xb6, 0xe6, 0x7e, 0x1b, 0xf8, 0xaa, 0xf2, 0xca, 0x8a, 0x0b, 0x8e,
	0xad, 0x34, 0x6f, 0x44, 0xba, 0xf1, 0x24, 0x64, 0x5e, 0x1b, 0xf4, 0x6e, 0x33, 0xce, 0xb3, 0x9c,
	0xfa, 0xa4, 0x64, 0x3e, 0x29, 0x0a, 0x2e, 0x88, 0x60, 0xbc, 0xa8, 0x95, 0xbe, 0xf7, 0xac, 0x25,
	0x39, 0xfb, 0x42, 0x04, 0xf5, 0x4f, 0x85, 0x6a, 0xb8, 0x3e, 0x58, 0x53, 0x2a, 0x42, 0xb9, 0x3b,
	0xa1, 0x5f, 0x1b, 0x5a, 0x0b, 0x7c, 0x03, 0x7a, 0x41, 0xb6, 0xd4, 0x46, 0x0e, 0xea, 0x9b, 0xc3,
	0x07, 0xbf, 0x86, 0x7a, 0xa5, 0x39, 0x28, 0x91, 0xd0, 0x8d, 0xe0, 0xf1, 0x5f, 0x03, 0x75, 0xc9,
	0x8b, 0x9a, 0xe2, 0xb7, 0x60, 0x28, 0x7b, 0x36, 0x72, 0x3a, 0xfd, 0xab, 0x81, 0xed, 0x5d, 0xfa,
	0xf3, 0x8e, 0x13, 0x47, 0x9d, 0xfb, 0x13, 0x81, 0xa1, 0x10, 0xbe, 0x05, 0x33, 0xdd, 0x90, 0x8a,
	0xa4, 0x82, 0x56, 0xea, 0x66, 0x72, 0x06, 0x18, 0x1f, 0xcd, 0x68, 0xb2, 0x21, 0x6b, 0xfc, 0x1a,
	0xae, 0xd5, 0x9a, 0x55, 0x4d, 0x2b, 0xc6, 0x69, 0x6d, 0x77, 0x64, 0xf7, 0xa1, 0xa2, 0x0b, 0x05,
	0xf1, 0x0d, 0x98, 0x6c, 0x4b, 0x32, 0xba, 0x6a, 0xaa, 0xdc, 0xd6, 0xa5, 0xa2, 0x2b, 0xc1, 0xb2,
	0xca, 0x71, 0x00, 0xba, 0xd8, 0x95, 0xd4, 0xbe, 0xef, 0xa0, 0xfe, 0xf5, 0xe0, 0xc5, 0xff, 0x0c,
	0x7b, 0x1f, 0x77, 0x25, 0x4d, 0xa4, 0xd4, 0x7d, 0x0f, 0xfa, 0xe1, 0x0b, 0x3f, 0x82, 0xab, 0xe5,
	0x6c, 0x31, 0x8f, 0x46, 0xf1, 0x24, 0x8e, 0xc6, 0xd6, 0x3d, 0xdc, 0x05, 0x7d, 0x14, 0x26, 0x63,
	0x0b, 0x61, 0x00, 0x63, 0x12, 0x4f, 0x97, 0x49, 0x64, 0x69, 0x07, 0xfa, 0x29, 0x4c, 0x66, 0x56,
	0x67, 0xb0, 0x47, 0x60, 0xaa, 0x75, 0xe1, 0x3c, 0xc6, 0x0d, 0x98, 0x7f, 0xfe, 0x20, 0x76, 0xff,
	0x3d, 0x7c, 0x99, 0x47, 0xef, 0xd5, 0x9d, 0x1a, 0x15, 0x81, 0xfb, 0x72, 0xff, 0xfd, 0xc7, 0x37,
	0xed, 0xb9, 0xfb, 0xe4, 0xfc, 0x56, 0xfc, 0xec, 0xa4, 0xfa, 0x80, 0xde, 0x0c, 0xe1, 0x73, 0x57,
	0xe1, 0x36, 0x58, 0x1b, 0x32, 0xfc, 0x77, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xec, 0x16, 0xed,
	0xeb, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AmiiboAPIClient is the client API for AmiiboAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AmiiboAPIClient interface {
	GetAmiibo(ctx context.Context, in *GetAmiiboRequest, opts ...grpc.CallOption) (*GetAmiiboResponse, error)
}

type amiiboAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAmiiboAPIClient(cc grpc.ClientConnInterface) AmiiboAPIClient {
	return &amiiboAPIClient{cc}
}

func (c *amiiboAPIClient) GetAmiibo(ctx context.Context, in *GetAmiiboRequest, opts ...grpc.CallOption) (*GetAmiiboResponse, error) {
	out := new(GetAmiiboResponse)
	err := c.cc.Invoke(ctx, "/clutch.amiibi.v1.AmiiboAPI/GetAmiibo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmiiboAPIServer is the server API for AmiiboAPI service.
type AmiiboAPIServer interface {
	GetAmiibo(context.Context, *GetAmiiboRequest) (*GetAmiiboResponse, error)
}

// UnimplementedAmiiboAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAmiiboAPIServer struct {
}

func (*UnimplementedAmiiboAPIServer) GetAmiibo(ctx context.Context, req *GetAmiiboRequest) (*GetAmiiboResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAmiibo not implemented")
}

func RegisterAmiiboAPIServer(s *grpc.Server, srv AmiiboAPIServer) {
	s.RegisterService(&_AmiiboAPI_serviceDesc, srv)
}

func _AmiiboAPI_GetAmiibo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAmiiboRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmiiboAPIServer).GetAmiibo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clutch.amiibi.v1.AmiiboAPI/GetAmiibo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmiiboAPIServer).GetAmiibo(ctx, req.(*GetAmiiboRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AmiiboAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clutch.amiibi.v1.AmiiboAPI",
	HandlerType: (*AmiiboAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAmiibo",
			Handler:    _AmiiboAPI_GetAmiibo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amiibo/v1/amiibo.proto",
}
